version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-json-rpc:
    container_name: zkevm-json-rpc
    image: chaindev001/zkevm-node
    ports:
      - 8545:8545
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=zkevm-rpc-db
      - ZKEVM_NODE_RPC_BROADCASTURI=moduluschaintestexplorer.cultdao.io:61090
    volumes:
      - ./acc.keystore:/pk/keystore
      - ./config/environments/public/public.node.config.toml:/app/config.toml
      - ./config/environments/public/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc"

  zkevm-sync:
    container_name: zkevm-sync
    image: chaindev001/zkevm-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./acc.keystore:/pk/keystore
      - ./config/environments/public/public.node.config.toml:/app/config.toml
      - ./config/environments/public/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components synchronizer"


  zkevm-broadcast:
    container_name: zkevm-broadcast
    image: chaindev001/zkevm-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    ports:
      - 61090:61090
    volumes:
      - ./acc.keystore:/pk/keystore
      - ./config/environments/public/public.node.config.toml:/app/config.toml
      - ./config/environments/public/public.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components broadcast-trusted-state"


  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/zkevm-node/.postgres-state:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]

  zkevm-pool-db:
    container_name: zkevm-pool-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5433:5432
    volumes:
      - ~/zkevm-node/.postgres-pool:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command: ["postgres", "-N", "500"]
    
  zkevm-rpc-db:
    container_name: zkevm-rpc-db
    image: postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5434:5432
    volumes:
      - ~/zkevm-node/.postgres-rpc:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rpc_user
      - POSTGRES_PASSWORD=rpc_password
      - POSTGRES_DB=rpc_db
    command: ["postgres", "-N", "500"]

  zkevm-prover:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:develop@sha256:408855e37f4751260bfb206e6aeb3b53c773a1615e8d675166b3647770700701
    ports:
      - 50051:50051 # Prover
      - 50061:50061 # MT
      - 50071:50071 # Executor
      
    volumes:
      - ./config/environments/public/public.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-explorer-db:
      container_name: zkevm-explorer-db
      image: postgres
      ports:
          - 5435:5432
      environment:
          - POSTGRES_USER=test_user
          - POSTGRES_PASSWORD=test_password
          - POSTGRES_DB=explorer

  zkevm-explorer:
      container_name: zkevm-explorer
      image: hermeznetwork/zkevm-explorer:latest
      ports:
          - 4000:4000
      environment:
          - NETWORK=POE
          - SUBNETWORK=Polygon Hermez
          - COIN=ETH
          - ETHEREUM_JSONRPC_VARIANT=geth
          - ETHEREUM_JSONRPC_HTTP_URL=http://zkevm-json-rpc:8545
          - DATABASE_URL=postgres://test_user:test_password@zkevm-explorer-db:5432/explorer
          - ECTO_USE_SSL=false
          - MIX_ENV=prod
          - LOGO=/images/blockscout_logo.svg
          - LOGO_FOOTER=/images/blockscout_logo.svg
      command: ["/bin/sh", "-c", "mix do ecto.create, ecto.migrate; mix phx.server"]

  zkevm-explorer-zknode:
    container_name: zkevm-explorer-zknode
    image: hermeznetwork/zkevm-node
    ports:
      - 8124:8124
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-pool-db
      - ZKEVM_NODE_RPC_DB_HOST=zkevm-rpc-db
      - ZKEVM_NODE_RPC_PORT=8124
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components rpc --http.api eth,net,debug,zkevm,txpool,web3"

  zkevm-bridge-db:
    container_name: zkevm-bridge-db
    image: postgres
    expose:
      - 5436
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: ["postgres", "-N", "500"]

  zkevm-bridge-service:
    container_name: zkevm-bridge-service
    image: hermeznetwork/zkevm-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=zkevm-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./config/environments/public/public.bridge.config.toml:/app/config.toml

    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-bridge run --cfg /app/config.toml"

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot

    zkevm-sequencer:
    container_name: zkevm-sequencer
    image: zkevm-node
    ports:
      - 9092:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_HOST=zkevm-pool-db
    volumes:
      - ./test.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components sequencer"

