[Log]
Level = "debug"
Outputs = ["stdout"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[PoolDB]
User = "pool_user"
Password = "pool_password"
Name = "pool_db"
Host = "zkevm-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Etherman]
URL = "https://goerli.infura.io/v3/cf298c535265448d8273f4d99ae80e5a"
L1ChainID = 5
PrivateKeyPath = "/pk/keystore"
PrivateKeyPassword = "testonly"
PoEAddr = "0x35B14aB1C8106500e4DDEB8576D84Ebf078E3526"
MaticAddr = "0x9242600cF556dD4F333D6d46d10D245c7564A411"
GlobalExitRootManagerAddr = "0x7cE48B29Df1204dbC2e9c10789a0240D48FC5A84"
MultiGasProvider = false
	[Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = "https://public.zkevm-test.net:2083"
BroadcastURI = "public-grpc.zkevm-test.net:61090"
DefaultSenderAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[RPC.DB]
User = "rpc_user"
Password = "rpc_password"
Name = "rpc_db"
Host = "zkevm-rpc-db"
Port = "5432"
EnableLog = false
MaxConns = 100

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 10000
TrustedSequencerURI = ""
GenBlockNumber = 7710669

[GasPriceEstimator]
Type = "default"
DefaultGasPriceWei = 1000000000

[MTClient]
URI = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
