[Log]
Level = "debug"
Outputs = ["stdout"]

[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5432"
MaxConns = 20

[Etherman]
L1URL = "https://goerli.infura.io/v3/51b9e8dcfe094e32986354b4fe93210a"
L2URLs = ["http://zkevm-json-rpc:8545"]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
GrpcURL = "54.216.111.98:61090"

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 1
PoEAddr = "0x307e6BC482B8c4AF11E42C2f812142c2B6B94342"
BridgeAddr = "0xcd8ECedd6d726c2E0Cd67EAd6F6206BeB1f6264A"
GlobalExitRootManAddr = "0xA0263151308F2098CAd27509203983f5525E2DD4"
MaticAddr = "0xe5f254F96711EC8220a876f4121325FB4c1009F1"
L2BridgeAddrs = ["0x9d98deabc42dd696deb9e40b4f1cab7ddbf55988"]
L1ChainID = 5