[Log]
Level = "debug"
Outputs = ["stdout"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[PoolDB]
User = "pool_user"
Password = "pool_password"
Name = "pool_db"
Host = "zkevm-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Etherman]
URL = "https://goerli.infura.io/v3/51b9e8dcfe094e32986354b4fe93210a"
L1ChainID = 5
PrivateKeyPath = "/pk/keystore"
PrivateKeyPassword = "testonly"
PoEAddr = "0x307e6BC482B8c4AF11E42C2f812142c2B6B94342"
MaticAddr = "0xe5f254F96711EC8220a876f4121325FB4c1009F1"
GlobalExitRootManagerAddr = "0xA0263151308F2098CAd27509203983f5525E2DD4"
MultiGasProvider = false
	[Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = "https://public.zkevm-test.net:2083"
BroadcastURI = "zkevm-broadcast:61090"
DefaultSenderAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[RPC.DB]
User = "rpc_user"
Password = "rpc_password"
Name = "rpc_db"
Host = "zkevm-rpc-db"
Port = "5432"
EnableLog = false
MaxConns = 100

[Synchronizer]
SyncInterval = "2s"
SyncChunkSize = 10000
TrustedSequencerURI = ""
GenBlockNumber = 7710669

[GasPriceEstimator]
Type = "default"
DefaultGasPriceWei = 1000000000

[MTClient]
URI = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = false
